


services:
  
  database:
    container_name: projecttolio-db
    image: postgres:16.3
    restart: always
    volumes:
      - projecttolio-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
volumes:
  projecttolio-db: